spring.application.name=config-server

#Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=config-server
eureka.instance.prefer-ip-address=true

# Config Server points to your remote Git repo
spring.cloud.config.server.git.uri=https://github.com/LakshyaRaghuwanshi/jobApp-application-config-repo/